public void test_error() throws Exception {
  Exception error=null;
  try {
    dataSource.init();
  }
 catch (  Exception e) {
    error=e;
  }
  Assert.assertNotNull(error);
}
