@Test public void getTimedOut() throws Exception {
  try {
    fo.get(1,TimeUnit.NANOSECONDS);
    fail("Should have thrown");
  }
 catch (  TimeoutException expected) {
    assertEquals(timeoutMessage(1,TimeUnit.NANOSECONDS),expected.getMessage());
  }
}
