@Test public void defaultExceptionsForExit(){
  Error error=new Error();
  TransactionTerminatedException terminatedException=new TransactionTerminatedException(Status.Transaction.Terminated);
  try {
    template.execute((Consumer<Transaction>)tx -> {
      throw error;
    }
);
  }
 catch (  TransactionFailureException ex) {
  }
  try {
    template.execute((Consumer<Transaction>)tx -> {
      throw terminatedException;
    }
);
  }
 catch (  TransactionFailureException ignored) {
  }
  assertThat(monitor.numRetry,is(0));
  assertThat(monitor.failures,contains(error,terminatedException));
  assertThat(monitor.fails,contains(error,terminatedException));
}
