private static class FakeClassUnderTest {
  public void throwsExceptionWithCause(){
    doThrowExceptionWithCause();
  }
  public void throwsExceptionWithoutCause(){
    doThrowExceptionWithoutCause();
  }
  private void doThrowExceptionWithCause(){
    try {
      throwsExceptionWithoutCause();
    }
 catch (    Exception e) {
      throw new RuntimeException("outer",e);
    }
  }
  private void doThrowExceptionWithoutCause(){
    throw new RuntimeException("cause");
  }
}
