@Test public void testClose() throws Exception {
  long timeoutMs=1000;
  executor.shutdown();
  PowerMock.expectLastCall();
  EasyMock.expect(executor.awaitTermination(eq(timeoutMs),eq(TimeUnit.MILLISECONDS))).andReturn(false);
  mockLog.error(EasyMock.anyString());
  PowerMock.expectLastCall();
  PowerMock.replayAll();
  committer.close(timeoutMs);
  PowerMock.verifyAll();
  PowerMock.resetAll();
  executor.shutdown();
  PowerMock.expectLastCall();
  EasyMock.expect(executor.awaitTermination(eq(timeoutMs),eq(TimeUnit.MILLISECONDS))).andThrow(new InterruptedException());
  PowerMock.replayAll();
  committer.close(timeoutMs);
  PowerMock.verifyAll();
}
