@Test public void hasNextCrash(){
  Single.just(1).flattenAsFlowable(new Function<Integer,Iterable<Integer>>(){
    @Override public Iterable<Integer> apply(    Integer v) throws Exception {
      return new CrashingIterable(100,1,100);
    }
  }
).test().assertFailureAndMessage(TestException.class,"hasNext()");
}
