public static class ExceptionThrower {
  private boolean catchInvoked;
  private boolean finallyInvoked;
  public boolean isCatchInvoked(){
    return catchInvoked;
  }
  public boolean isFinallyInvoked(){
    return finallyInvoked;
  }
  public void doTest() throws Exception {
    try {
      throw new ApplicationContextException("foo");
    }
 catch (    Exception ex) {
      catchInvoked=true;
      throw ex;
    }
 finally {
      finallyInvoked=true;
    }
  }
}
